spring.application.name=rent-payment-financial-platform
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/rent_payment}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:rent_payment}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:rent_payment}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true
